/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Rol;

/**
 *
 * @author jega_
 */
public class frmEliminarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmEliminarUsuario
     */
    public frmEliminarUsuario() {
        initComponents();
        txtNombre.setEnabled(false);
        txtUsuario.setEnabled(false);
        txtClave.setEnabled(false);
        jcombRol.setEnabled(false);
        btnEliminar.setEnabled(false);
    }
    
    //Getters
    public javax.swing.JButton getBtnBuscar() {
        return btnBuscar;
    }
    
    public javax.swing.JTextField getTxtIdUsuario() {
        return txtIdUsuario;
    }
    
    public javax.swing.JTextField getTxtNombre(){
        return txtNombre;
    }
    
    public javax.swing.JTextField getTxtUsuario(){
        return txtUsuario;
    }
    
    public javax.swing.JPasswordField getTxtClave() {
        return txtClave;
    }
    
    public javax.swing.JComboBox getcmbRol() {
        return jcombRol;
    }
    
    public javax.swing.JButton getBtnEliminar() {
        return btnEliminar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBack = new javax.swing.JPanel();
        txtClave = new Custom.RoundPasswordField(7);
        btnEliminar = new Custom.RoundButton("Eliminar Usuario");
        etiClave = new javax.swing.JLabel();
        txtUsuario = new Custom.RoundTextField(7);
        etiUsuario = new javax.swing.JLabel();
        jcombRol = new javax.swing.JComboBox<>();
        etiRol = new javax.swing.JLabel();
        IconNewUser = new Custom.ImagenPanel("/Resources/delete.png");
        etiNombre = new javax.swing.JLabel();
        txtNombre = new Custom.RoundTextField(7);
        etiIdUsuario = new javax.swing.JLabel();
        txtIdUsuario = new Custom.RoundTextField(7);
        btnBuscar = new Custom.RoundButton("Buscar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpBack.setBackground(new java.awt.Color(255, 255, 255));
        jpBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtClave.setEditable(false);
        txtClave.setBackground(new java.awt.Color(244, 244, 244));
        txtClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        jpBack.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 260, 40));

        btnEliminar.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar Usuario");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jpBack.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 260, 40));

        etiClave.setBackground(new java.awt.Color(0, 0, 0));
        etiClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiClave.setForeground(new java.awt.Color(0, 0, 0));
        etiClave.setText("Clave del usuario");
        jpBack.add(etiClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(244, 244, 244));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jpBack.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 260, 40));

        etiUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiUsuario.setForeground(new java.awt.Color(0, 0, 0));
        etiUsuario.setText("Usuario");
        jpBack.add(etiUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jcombRol.setBackground(new java.awt.Color(244, 244, 244));
        jcombRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcombRol.setEnabled(false);
        jcombRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombRolActionPerformed(evt);
            }
        });
        jpBack.add(jcombRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 260, 50));

        etiRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiRol.setForeground(new java.awt.Color(0, 0, 0));
        etiRol.setText("Rol del usuario");
        jpBack.add(etiRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        javax.swing.GroupLayout IconNewUserLayout = new javax.swing.GroupLayout(IconNewUser);
        IconNewUser.setLayout(IconNewUserLayout);
        IconNewUserLayout.setHorizontalGroup(
            IconNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        IconNewUserLayout.setVerticalGroup(
            IconNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jpBack.add(IconNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 120));

        etiNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiNombre.setForeground(new java.awt.Color(0, 0, 0));
        etiNombre.setText("Nombre del trabajador");
        jpBack.add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(244, 244, 244));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jpBack.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 260, 40));

        etiIdUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiIdUsuario.setForeground(new java.awt.Color(0, 0, 0));
        etiIdUsuario.setText("ID del usuario");
        jpBack.add(etiIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        txtIdUsuario.setBackground(new java.awt.Color(244, 244, 244));
        txtIdUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActionPerformed(evt);
            }
        });
        jpBack.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 170, 40));

        btnBuscar.setBackground(new java.awt.Color(238, 217, 75));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpBack.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBack, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jcombRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombRolActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEliminarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IconNewUser;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel etiClave;
    private javax.swing.JLabel etiIdUsuario;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiRol;
    private javax.swing.JLabel etiUsuario;
    private javax.swing.JComboBox<Rol> jcombRol;
    private javax.swing.JPanel jpBack;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
