/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Custom.IconScaler;
import Main.App;
import Security.Permisos;
import java.util.Set;

public class frmMenu extends javax.swing.JFrame {

    private String rolActual;
    
    public frmMenu(String rolActual) {
        this.rolActual = rolActual;
        initComponents();
        setLocationRelativeTo(null);
        setIcons();
        aplicarPermisos(rolActual);
    }
    
    private void setIcons() {
        int size = 24; // tamaño de los íconos
        OpcionesLayout.setIconAt(0, IconScaler.getScaledIcon("/Resources/opIcons/Dashboard.png", size, size));
        OpcionesLayout.setIconAt(1, IconScaler.getScaledIcon("/Resources/opIcons/Productos.png", size, size));
        OpcionesLayout.setIconAt(2, IconScaler.getScaledIcon("/Resources/opIcons/Ventas.png", size, size));
        OpcionesLayout.setIconAt(3, IconScaler.getScaledIcon("/Resources/opIcons/Proveedores.png", size, size));
        OpcionesLayout.setIconAt(4, IconScaler.getScaledIcon("/Resources/opIcons/Factura.png", size, size));
        OpcionesLayout.setIconAt(5, IconScaler.getScaledIcon("/Resources/opIcons/Usuarios.png", size, size));
    }

    private void aplicarPermisos(String rol) {
    Set<String> permisos = Permisos.getPermisos(rol);

    if (!permisos.contains("Dashboard")) {
        OpcionesLayout.remove(jpDashboard);
    }
    if (!permisos.contains("Productos")) {
        OpcionesLayout.remove(jpProductos);
    }
    if (!permisos.contains("Ventas")) {
        OpcionesLayout.remove(jpVentas);
    }
    if (!permisos.contains("Proveedores")) {
        OpcionesLayout.remove(jpProveedores);
    }
    if (!permisos.contains("Facturas")) {
        OpcionesLayout.remove(jpFacturas);
    }
    if (!permisos.contains("Usuarios")) {
        OpcionesLayout.remove(jpUsuarios);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionesLayout = new javax.swing.JTabbedPane();
        jpDashboard = new javax.swing.JPanel();
        jpProductos = new javax.swing.JPanel();
        jpVentas = new javax.swing.JPanel();
        jpProveedores = new javax.swing.JPanel();
        jpFacturas = new javax.swing.JPanel();
        jpUsuarios = new javax.swing.JPanel();
        brrMenu = new javax.swing.JMenuBar();
        opSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OpcionesLayout.setBackground(new java.awt.Color(238, 217, 75));
        OpcionesLayout.setForeground(new java.awt.Color(0, 0, 0));
        OpcionesLayout.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        OpcionesLayout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        OpcionesLayout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jpDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpDashboardLayout = new javax.swing.GroupLayout(jpDashboard);
        jpDashboard.setLayout(jpDashboardLayout);
        jpDashboardLayout.setHorizontalGroup(
            jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1176, Short.MAX_VALUE)
        );
        jpDashboardLayout.setVerticalGroup(
            jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        OpcionesLayout.addTab("Dashboard", jpDashboard);

        jpProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpProductosLayout = new javax.swing.GroupLayout(jpProductos);
        jpProductos.setLayout(jpProductosLayout);
        jpProductosLayout.setHorizontalGroup(
            jpProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1176, Short.MAX_VALUE)
        );
        jpProductosLayout.setVerticalGroup(
            jpProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        OpcionesLayout.addTab("Productos", jpProductos);

        jpVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpVentasLayout = new javax.swing.GroupLayout(jpVentas);
        jpVentas.setLayout(jpVentasLayout);
        jpVentasLayout.setHorizontalGroup(
            jpVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1176, Short.MAX_VALUE)
        );
        jpVentasLayout.setVerticalGroup(
            jpVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        OpcionesLayout.addTab("Ventas", jpVentas);

        jpProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpProveedoresLayout = new javax.swing.GroupLayout(jpProveedores);
        jpProveedores.setLayout(jpProveedoresLayout);
        jpProveedoresLayout.setHorizontalGroup(
            jpProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1176, Short.MAX_VALUE)
        );
        jpProveedoresLayout.setVerticalGroup(
            jpProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        OpcionesLayout.addTab("Proveedores", jpProveedores);

        jpFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpFacturasLayout = new javax.swing.GroupLayout(jpFacturas);
        jpFacturas.setLayout(jpFacturasLayout);
        jpFacturasLayout.setHorizontalGroup(
            jpFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1176, Short.MAX_VALUE)
        );
        jpFacturasLayout.setVerticalGroup(
            jpFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        OpcionesLayout.addTab("Facturas", jpFacturas);

        jpUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpUsuariosLayout = new javax.swing.GroupLayout(jpUsuarios);
        jpUsuarios.setLayout(jpUsuariosLayout);
        jpUsuariosLayout.setHorizontalGroup(
            jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1176, Short.MAX_VALUE)
        );
        jpUsuariosLayout.setVerticalGroup(
            jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        OpcionesLayout.addTab("Usuarios", jpUsuarios);

        brrMenu.setBackground(new java.awt.Color(0, 0, 0));
        brrMenu.setForeground(new java.awt.Color(255, 255, 255));

        opSalir.setText("Salir");
        opSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opSalirMouseClicked(evt);
            }
        });
        opSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSalirActionPerformed(evt);
            }
        });
        brrMenu.add(opSalir);

        setJMenuBar(brrMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OpcionesLayout)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OpcionesLayout)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSalirActionPerformed
   
    }//GEN-LAST:event_opSalirActionPerformed

    private void opSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opSalirMouseClicked
        this.dispose();      
        App.abrirLogin(); 
    }//GEN-LAST:event_opSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu("Admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane OpcionesLayout;
    private javax.swing.JMenuBar brrMenu;
    private javax.swing.JPanel jpDashboard;
    private javax.swing.JPanel jpFacturas;
    private javax.swing.JPanel jpProductos;
    private javax.swing.JPanel jpProveedores;
    private javax.swing.JPanel jpUsuarios;
    private javax.swing.JPanel jpVentas;
    private javax.swing.JMenu opSalir;
    // End of variables declaration//GEN-END:variables
}
