/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import com.sun.source.tree.SwitchTree;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jega_
 */
public class frmNuevoProveedor extends javax.swing.JFrame {

    /**
     * Creates new form frmNuevoProveedor
     */
    public frmNuevoProveedor() {
        initComponents();
    }
    
    //Getters
    public javax.swing.JTextField getTxtNombre() {
        return txtNombre;
    }
    
    public javax.swing.JTextField getTxtEmail() {
        return txtEmail;
    }
    
    public javax.swing.JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBack = new javax.swing.JPanel();
        btnRegistrar = new Custom.RoundButton("Registrar nuevo usuario");
        txtEmail = new Custom.RoundTextField(7);
        etiEmail = new javax.swing.JLabel();
        IconNewUser = new Custom.ImagenPanel("/Resources/logoIcon.png");
        etiNombre = new javax.swing.JLabel();
        txtNombre = new Custom.RoundTextField(7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpBack.setBackground(new java.awt.Color(255, 255, 255));
        jpBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(238, 217, 75));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("Registrar nuevo proveedor");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jpBack.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 260, 40));

        txtEmail.setBackground(new java.awt.Color(244, 244, 244));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jpBack.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 260, 40));

        etiEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiEmail.setForeground(new java.awt.Color(0, 0, 0));
        etiEmail.setText("Email");
        jpBack.add(etiEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        javax.swing.GroupLayout IconNewUserLayout = new javax.swing.GroupLayout(IconNewUser);
        IconNewUser.setLayout(IconNewUserLayout);
        IconNewUserLayout.setHorizontalGroup(
            IconNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        IconNewUserLayout.setVerticalGroup(
            IconNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jpBack.add(IconNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 130, 120));

        etiNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiNombre.setForeground(new java.awt.Color(0, 0, 0));
        etiNombre.setText("Nombre del proveedor");
        jpBack.add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        txtNombre.setBackground(new java.awt.Color(244, 244, 244));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jpBack.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBack, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNuevoProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IconNewUser;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel etiEmail;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JPanel jpBack;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
