/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Rol;
import Model.TrabajadorDAO;

/**
 *
 * @author jega_
 */
public class frmNuevoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmNuevoUsuario
     */
    public frmNuevoUsuario() {
        initComponents();
        cargarRoles();
    }
    
 // Getters
    public javax.swing.JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public javax.swing.JTextField getTxtNombre() {
        return txtNombre;
    }

    public javax.swing.JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public javax.swing.JPasswordField getTxtClave() {
        return txtClave;
    }

    public javax.swing.JComboBox<Rol> getCmbRol() {
        return jcombRol;
    }
    
    public void limpiarCampos() {
        txtNombre.setText("");
        txtUsuario.setText("");
        txtClave.setText("");
        jcombRol.setSelectedIndex(0);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBack = new javax.swing.JPanel();
        txtClave = new Custom.RoundPasswordField(7);
        btnRegistrar = new Custom.RoundButton("Registrar nuevo usuario");
        etiClave = new javax.swing.JLabel();
        txtUsuario = new Custom.RoundTextField(7);
        etiUsuario = new javax.swing.JLabel();
        jcombRol = new javax.swing.JComboBox<>();
        etiRol = new javax.swing.JLabel();
        IconNewUser = new Custom.ImagenPanel("/Resources/logoIcon.png");
        etiNombre = new javax.swing.JLabel();
        txtNombre = new Custom.RoundTextField(7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBack.setBackground(new java.awt.Color(255, 255, 255));
        jpBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtClave.setBackground(new java.awt.Color(244, 244, 244));
        txtClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        jpBack.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 260, 40));

        btnRegistrar.setBackground(new java.awt.Color(238, 217, 75));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("Registrar nuevo usuario");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jpBack.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 260, 40));

        etiClave.setBackground(new java.awt.Color(0, 0, 0));
        etiClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiClave.setForeground(new java.awt.Color(0, 0, 0));
        etiClave.setText("Clave del usuario");
        jpBack.add(etiClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(244, 244, 244));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jpBack.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 260, 40));

        etiUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiUsuario.setForeground(new java.awt.Color(0, 0, 0));
        etiUsuario.setText("Usuario");
        jpBack.add(etiUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jcombRol.setBackground(new java.awt.Color(244, 244, 244));
        jcombRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcombRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombRolActionPerformed(evt);
            }
        });
        jpBack.add(jcombRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 260, 50));

        etiRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiRol.setForeground(new java.awt.Color(0, 0, 0));
        etiRol.setText("Rol del usuario");
        jpBack.add(etiRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        javax.swing.GroupLayout IconNewUserLayout = new javax.swing.GroupLayout(IconNewUser);
        IconNewUser.setLayout(IconNewUserLayout);
        IconNewUserLayout.setHorizontalGroup(
            IconNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        IconNewUserLayout.setVerticalGroup(
            IconNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jpBack.add(IconNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 120));

        etiNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiNombre.setForeground(new java.awt.Color(0, 0, 0));
        etiNombre.setText("Nombre del trabajador");
        jpBack.add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        txtNombre.setBackground(new java.awt.Color(244, 244, 244));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jpBack.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBack, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBack, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jcombRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombRolActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    //LLenar JcomboBox
    private void cargarRoles() {
        TrabajadorDAO dao = new TrabajadorDAO();
        java.util.List<Rol> roles = dao.listarRoles();
        jcombRol.removeAllItems(); // Limpiamos antes de cargar

        for (Rol r : roles) {
            jcombRol.addItem(r);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IconNewUser;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel etiClave;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiRol;
    private javax.swing.JLabel etiUsuario;
    private javax.swing.JComboBox<Rol> jcombRol;
    private javax.swing.JPanel jpBack;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
