package View;


public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorLogin = new javax.swing.JPanel();
        Imagen = new Custom.ImagenPanel("/Resources/Fondo.png");
        etiUsuario = new javax.swing.JLabel();
        etiContraseña = new javax.swing.JLabel();
        txtUsuario = new Custom.RoundTextField(7);
        btnIngresar = new Custom.RoundButton("Ingresar");
        IconoLogin = new Custom.ImagenPanel("/Resources/IconoLogin.png");
        etiLogo = new javax.swing.JLabel();
        etiLogo2 = new javax.swing.JLabel();
        txtClave = new Custom.RoundPasswordField(7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGVI - FERRETERIA");
        setResizable(false);

        ContenedorLogin.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout ImagenLayout = new javax.swing.GroupLayout(Imagen);
        Imagen.setLayout(ImagenLayout);
        ImagenLayout.setHorizontalGroup(
            ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        ImagenLayout.setVerticalGroup(
            ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        ContenedorLogin.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 630, 660));

        etiUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiUsuario.setForeground(new java.awt.Color(0, 0, 0));
        etiUsuario.setText("Usuario");
        ContenedorLogin.add(etiUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        etiContraseña.setBackground(new java.awt.Color(0, 0, 0));
        etiContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiContraseña.setForeground(new java.awt.Color(0, 0, 0));
        etiContraseña.setText("Contraseña");
        ContenedorLogin.add(etiContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(244, 244, 244));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        ContenedorLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 260, 40));

        btnIngresar.setBackground(new java.awt.Color(238, 217, 75));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        ContenedorLogin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 260, 40));

        javax.swing.GroupLayout IconoLoginLayout = new javax.swing.GroupLayout(IconoLogin);
        IconoLogin.setLayout(IconoLoginLayout);
        IconoLoginLayout.setHorizontalGroup(
            IconoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        IconoLoginLayout.setVerticalGroup(
            IconoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        ContenedorLogin.add(IconoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, 140));

        etiLogo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        etiLogo.setForeground(new java.awt.Color(0, 0, 0));
        etiLogo.setText("SGVI | ");
        ContenedorLogin.add(etiLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        etiLogo2.setForeground(new java.awt.Color(0, 0, 0));
        etiLogo2.setText("Sistema de Gestión de Ventas e Inventario");
        ContenedorLogin.add(etiLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 30));

        txtClave.setBackground(new java.awt.Color(244, 244, 244));
        txtClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        ContenedorLogin.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    // Getters
    public javax.swing.JButton getBtnIngresar() {
        return btnIngresar;
    }

    public javax.swing.JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public javax.swing.JPasswordField getTxtClave() {
        return txtClave;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            LoginView login = new LoginView();
            Model.TrabajadorDAO dao = new Model.TrabajadorDAO();
            new Controller.LoginController(login, dao);
            login.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorLogin;
    private javax.swing.JPanel IconoLogin;
    private javax.swing.JPanel Imagen;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel etiContraseña;
    private javax.swing.JLabel etiLogo;
    private javax.swing.JLabel etiLogo2;
    private javax.swing.JLabel etiUsuario;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
